# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  # Enable version updates for root npm
  - package-ecosystem: 'npm'
    # Look for `package.json` and `lock` files in the `root` directory
    directory: '/'
    # Check the npm registry for updates every day (weekdays)
    schedule:
      interval: 'daily'
      time: '07:00'
      timezone: 'Europe/Paris'
    target-branch: 'dev'
    commit-message:
      prefix: 'chore(deps-npm): '
    open-pull-requests-limit: 5
    ignore:
      - dependency-name: '*'
      - dependency-name: '@nx/*'
      - dependency-name: 'nx'
        update-types: ['version-update:semver-patch']
    assignees:
      - 'Rangoow'
    reviewers:
      - 'Rangoow'
    labels:
      - 'Dependencies :package:'

  # Enable version updates for GitHub actions
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'
    target-branch: 'dev'
    commit-message:
      prefix: 'chore(deps-gh-actions): '
    labels:
      - 'Dependencies :package:'
      - 'Actions :rocket:'
