plugins:
  eslint:
    enabled: true
    config:
      config: './.eslintrc.js'
      extensions:
        - '.ts'
        - '.tsx'
        - '.js'
exclude_patterns:
  - '**/*.config.js'
  - '**/*.test.ts*'
  - '**/.eslintrc.js'
  - '**/tests/**'
