plugins:
  eslint:
    enabled: true
    config:
      config: '.eslintrc.js'
      extensions:
        - '.ts'
        - '.tsx'
        - '.js'
exclude_patterns:
  - '**/*.config.js'
  - '**/*.config.ts'
  - '**/*.test.ts*'
  - '**/.eslintrc.js'
  - '**/tests/**'
  - '**/index.ts'
