---
engines:
  duplication:
    exclude_paths:
      - '**/*.test.*'
      - '**/.eslintrc.js'
      - '**/tests/**'
exclude_paths:
  - '**/*.test.ts'
  - '**/*.test.tsx'
  - '**/tests/**'
  - '**/.eslintrc.js'
