name: Pull Request Workflow
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  laboratory_integration:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Nx set shas
        uses: nrwl/nx-set-shas@v3

      - name: Install dependencies
        run: npm ci

      - name: Lint affected
        run: npx nx affected -t lint --parallel=3

      - name: Test affected
        run: npx nx affected -t test --parallel=3 --configuration=ci

      - name: Build affected
        run: npx nx affected -t build --parallel=3

      - name: Build storybook affected
        run: npx nx affected -t build-storybook --parallel=3 --configuration=ci

      - name: Publish code coverage
        uses: paambaati/codeclimate-action@v4.0.0
        env:
          CC_TEST_REPORTER_ID: ${{secrets.CC_TEST_REPORTER_ID}}
        with:
          debug: true
          coverageCommand: npx nx affected -t test --parallel=3 --configuration=ci
          coverageLocations: |
            ${{github.workspace}}/coverage/apps/lcov.info:lcov
            ${{github.workspace}}/coverage/libs/lcov.info:lcov

